CREATE DATABASE BLACKJUMP;
USE BLACKJUMP;

CREATE TABLE IF NOT EXISTS GENERO(
ID_GEN INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE_GEN VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS CATEGORIA(
ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE_CATE VARCHAR(100) NOT NULL,
ESTADO_CATE INT DEFAULT 1 NOT NULL,
FK_ID_GEN INT,
FOREIGN KEY (FK_ID_GEN) REFERENCES GENERO (ID_GEN)
);
SELECT *FROM CATEGORIA;

CREATE TABLE IF NOT EXISTS ROLES(
ID_ROL INT AUTO_INCREMENT PRIMARY KEY,
ASING_ROL VARCHAR(400)
); 
SELECT *FROM ROLES;

CREATE TABLE IF NOT EXISTS PAIS(
ID_PAIS INT AUTO_INCREMENT PRIMARY KEY
);
SELECT *FROM PAIS;

CREATE TABLE IF NOT EXISTS CIUDAD(
ID_CIUDAD INT AUTO_INCREMENT PRIMARY KEY
);
SELECT *FROM CIUDAD;

CREATE TABLE IF NOT EXISTS ESTADO(
ID_ESTADO INT AUTO_INCREMENT PRIMARY KEY
);
SELECT *FROM ESTADO;

CREATE TABLE IF NOT EXISTS UBICACION(
ID_UBI INT AUTO_INCREMENT PRIMARY KEY,
DIRECCION VARCHAR(200) NOT NULL,
FK_ID_PAIS INT,
FOREIGN KEY (FK_ID_PAIS) REFERENCES PAIS (ID_PAIS),
FK_ID_CIUDAD INT,
FOREIGN KEY (FK_ID_CIUDAD) REFERENCES CIUDAD (ID_CIUDAD),
FK_ID_ESTADO INT,
FOREIGN KEY (FK_ID_ESTADO) REFERENCES ESTADO (ID_ESTADO),
FK_ID_USER INT,
FOREIGN KEY (FK_ID_USER) REFERENCES USUARIOS (ID_USER)
);
SELECT *FROM UBICACION;

CREATE TABLE IF NOT EXISTS TALLAS(
ID_TALLA INT AUTO_INCREMENT PRIMARY KEY,
TALLA_CABEZA VARCHAR(10),
TALLA_CBC VARCHAR(10),
TALLA_PANTALONES_WAIST DECIMAL(10,2),
TALLA_PANTALONES_LENGTH VARCHAR(10)
);
SELECT *FROM TALLAS;

CREATE TABLE IF NOT EXISTS USUARIOS(
ID_USER INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE_USER VARCHAR(100) NOT NULL,
APELLIDO_USER VARCHAR(100) NOT NULL,
CORREO_USER VARCHAR(30) UNIQUE,
PASSWORD_USER VARCHAR(255),
CONSTRAINT PASSWORD_USER CHECK (LENGTH(PASSWORD_USER) > 8),
DIRECCION VARCHAR(50),
TELEFONO VARCHAR(13),
FK_ID_ROL INT DEFAULT 2,
FOREIGN KEY (FK_ID_ROL) REFERENCES ROLES(ID_ROL),
FK_ID_TALLA INT,
FOREIGN KEY (FK_ID_TALLA) REFERENCES TALLAS (ID_TALLA)
);
SELECT *FROM USUARIOS;


CREATE TABLE IF NOT EXISTS PRODUCTO(
ID_PRODUCTO INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE_PRODUCTO VARCHAR(100) NOT NULL,
DESCRIP_PRODUCTO VARCHAR(500), 
ESTADO_PRODUCTO INT DEFAULT 1 NOT NULL,
CONSTRAINT ESTADO_PRODUCTO CHECK (ESTADO_PRODUCTO BETWEEN 0 AND 1),
GEN VARCHAR(30),
TALLA_GO VARCHAR(20),
TALLA_CA VARCHAR(20),
TALLA_PA VARCHAR(20),
CANTIDAD_PRODUCTO INT, 
PRECIO DECIMAL(10,2),
IMAGEN VARCHAR(800),
FK_ID_CATEGORIA INT ,
FOREIGN KEY (FK_ID_CATEGORIA) REFERENCES CATEGORIA (ID_CATEGORIA)
);
SELECT *FROM PRODUCTO;

CREATE TABLE IF NOT EXISTS COMPRA(
ID_COMPRA INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE_USER VARCHAR(100),
DIRECCION VARCHAR(100),
TOTAL_PA DECIMAL(10.2),
IVA DECIMAL(5,2) NOT NULL DEFAULT 19.00
);
SELECT *FROM COMPRA;

CREATE TABLE IF NOT EXISTS MPAGO(
ID_MPAGO INT AUTO_INCREMENT PRIMARY KEY,
NOM_MPAGO VARCHAR(250) NOT NULL,
TIPO_MPAGO VARCHAR(100) NOT NULL,
NOM_TITULAR VARCHAR(250) NOT NULL,
NUM_CUENTA VARCHAR(250),
FECHA_EXPI DATE,
COD_SEGURIDAD VARCHAR(10),
FECHA_MPAGO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ESTADO ENUM('ACTIVO','INACTIVO','PENDIENTE') DEFAULT 'ACTIVO',
FK_ID_COMPRA INT,
FOREIGN KEY (FK_ID_COMPRA) REFERENCES COMPRA (ID_COMPRA)
);
SELECT *FROM MPOGO;

CREATE TABLE IF NOT EXISTS FACTURA(
CODIGO_RECIVO INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE_USER VARCHAR(100) NOT NULL,
NOMBRE_PRO VARCHAR(100) NOT NULL,
DATE_RECIBO DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
CANTIDAD INT NOT NULL,
TOTAL_PA_C_IVA DECIMAL(10,2),
FK_ID_COMPRA INT,
FOREIGN KEY (FK_ID_COMPRA) REFERENCES COMPRA (ID_COMPRA)
);
SELECT *FROM FACTURA;

CREATE TABLE IF NOT EXISTS CARRITO (
SUBTOTAL DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
CANTIDAD INT NOT NULL DEFAULT 1,
FK_ID_COMPRA INT,
FOREIGN KEY (FK_ID_COMPRA) REFERENCES COMPRA (ID_COMPRA),
FK_ID_PRODUCTO INT,
FOREIGN KEY (FK_ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO),
FK_ID_USER INT,
FOREIGN KEY (FK_ID_USER) REFERENCES USUARIOS (ID_USER)
);
SELECT *FROM CARRITO;

/*INSERS INTOS*/

/*INSER INTO ROLES*/
INSERT INTO ROLES (ASING_ROL) VALUES ('Adim');
INSERT INTO ROLES (ASING_ROL) VALUES ('Usuario');

/*INSERT INTO USUARIOS*/
INSERT INTO USUARIOS (NOMBRE_USER, APELLIDO_USER, CORREO_USER, PASSWORD_USER)VALUES ('Alex', 'Martinez', 'martinezalexestiven2@gmail.com', '3054404112');
INSERT INTO USUARIOS (NOMBRE_USER, APELLIDO_USER, CORREO_USER, PASSWORD_USER)VALUES ('Lu', 'Montoya', 'Lumontoya@gmail.com', '3142470445');
INSERT INTO USUARIOS (NOMBRE_USER, APELLIDO_USER, CORREO_USER, PASSWORD_USER)VALUES ('Juan', 'Blandon', 'Juanblandon@gmail.com', '987654321');
INSERT INTO USUARIOS (NOMBRE_USER, APELLIDO_USER, CORREO_USER, PASSWORD_USER)VALUES ('Mateo', 'Amariles', 'mateoamariles2304@gmail.com', '123456789');
INSERT INTO USUARIOS (NOMBRE_USER, APELLIDO_USER, CORREO_USER, PASSWORD_USER)VALUES ('Lucas', 'Montoya', 'Lucasmontoya@gmail.com', '1234567890');
INSERT INTO USUARIOS (NOMBRE_USER, APELLIDO_USER, CORREO_USER, PASSWORD_USER)VALUES ('Luis', 'Montoya', 'Luismontoya@gmail.com', '234567890');

/*INSERT INTO CATEGORIAS*/

/*INSERT INTO PRODUCTOS*/